# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

# Custom config for development

def datacapture_core_plugin_path
  generated_flutter_plugins_file = File.expand_path(File.join('..', '..', '.flutter-plugins'), __FILE__)
  unless File.exist?(generated_flutter_plugins_file)
    raise "#{generated_flutter_plugins_file} must exist. Make sure flutter pub get is executed first."
  end
  File.foreach(generated_flutter_plugins_file) do |line|
    matches = line.match(/scandit_flutter_datacapture_core\=(.*)/)
    return matches[1].strip if matches
  end
  raise "scandit_flutter_datacapture_core not found in #{generated_flutter_plugins_file}. Try deleting the .flutter-plugins file, then run flutter pub get"
end

# End custom config for development

require File.expand_path(File.join(datacapture_core_plugin_path, 'scripts', 'detect_frameworks'))

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  pod 'scandit-datacapture-frameworks-core', :path => podspec_path_for_pod('scandit-datacapture-frameworks-core', File.expand_path('.'))
  pod 'scandit-datacapture-frameworks-barcode', :path => podspec_path_for_pod('scandit-datacapture-frameworks-barcode', File.expand_path('.'))

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'

      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',
        'PERMISSION_CAMERA=1',
      ]
    end
  end
end
